version: '3.8'
services:
  sd:
    container_name: sd
    restart: unless-stopped
    tty: true
    build:
      context: .
    ports:
      - ${WEBUI_PORT:-7860}:7860
    volumes:
      - "./extensions:/opt/sd/extensions"
      - "./modules:/opt/sd/modules"
      - "./models:/opt/sd/models"
    environment:
      CLI_ARGS: "--skip-version-check --allow-code --enable-insecure-extension-access --api --xformers --opt-channelslast"
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]
