version: '3.9'
services:
  stablediff:
    container_name: stablediff
    restart: unless-stopped
    tty: true
    user: root
    build:
      context: 'https://raw.githubusercontent.com/iTeeLion/stablediffusion_docker/main/Dockerfile'
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - ${WEBUI_PORT:-7860}:7860
    #command: bash -c 'chown -R sd:sd /opt/sd && tail -F /dev/null'
    command: bash -c 'chown -R sd:sd /opt/sd && sudo -u sd /opt/sd/entrypoint.sh $$CLI_ARGS'
    volumes:
      - "./extensions:/opt/sd/extensions"
      - "./modules:/opt/sd/modules"
      - "./models:/opt/sd/models"
    environment:
      #--api --enable-insecure-extension-access --allow-code --skip-version-check --opt-channelslast
      CLI_ARGS: ${CLI_ARGS:-"--api"}
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]
